#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
#bspc config window_gap 10
#bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme alternate

#bspc config normal_border_color "#282a2e"
#bspc config focused_border_color "#969896"
#bspc config presel_feedback_color "#969896"

bspc config normal_border_color "#1d1f21"
bspc config focused_border_color "#282a2e"
bspc config presel_feedback_color "#282a2e"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
